name: Grupo de Usuários WordPress Brasil
pygments: true
permalink: /:categories/:title/
exclude: [".editorconfig", "Rakefile", "README.md", "config.rb", "Gemfile*"]
baseurl: http://wpbrasil.github.io/wp.org.br/
destination: ./_build
deploy: ./_deploy
git:
  branch: gh-pages
  user: wpbrasil
  repo: wp.org.br
