name: Grupo de Usuários WordPress Brasil
pygments: true
permalink: /:categories/:title/
exclude: [".editorconfig", "Rakefile", "README.md", "config.rb", "Gemfile*"]
baseurl: http://wp.org.br/
destination: ./_build
deploy: ./_deploy
git:
  branch: master
  user: wpbrasil
  repo: wpbrasil.github.io
