name: Grupo de Usuários WordPress Brasil
pygments: true
permalink: /:categories/:title/
exclude: [".editorconfig", "Rakefile", "README.md", "config.rb"]
production_url: http://wp.org.br
git:
  branch: gh-pages
